### ISSUE TITLE
Alt attribuut bij logo

### ISSUE THREAD

**Issue by KrijnHoetmer** [rosahoffer/the-client-case#1]
Probeer bij images altijd een `alt` attribuut toe te voegen, zeker bij logo's. Vraag je af, “wat zou ik hier zeggen als ik dit aan iemand aan de telefoon voor zou lezen”?

https://github.com/rosahoffer/the-client-case/blob/4db2cc964f14f8aec5a0d3a9df6f2cf104b35a0f/index.html#L26

**Comment by rosahoffer** [comment]
Thanks, heb het aangepast!
